/** Shared Canada industries used across service pages */
export const CANADA_INDUSTRIES = [
  "Professional Service Firms",
  "Construction Companies",
  "Retail Businesses",
  "E-Commerce Businesses",
  "Manufacturing Companies",
  "Healthcare Providers",
  "Hospitality Businesses",
  "Real Estate Businesses",
  "Transportation & Logistics",
  "Technology Companies",
];

export const CANADA_WHY_CHOOSE_DEFAULT = [
  "CPA-Led Delivery Team",
  "Canadian Accounting Expertise",
  "CRA Compliance Knowledge",
  "White-Label Service Delivery",
  "Dedicated Offshore Resources",
  "Structured Review Processes",
  "Secure Data Handling",
  "Flexible Engagement Models",
  "Scalable Support Framework",
];

export const bookkeepingSoftware = [
  {
    heading: "ACCOUNTING SOFTWARE",
    icon: "user",
    logos: ["quickbooks online", "xero", "sage business cloud", "iris accounts production"],
  },
  {
    heading: "DOCUMENT PROCESSING TOOLS",
    icon: "document",
    logos: ["dext", "hubdoc", "autoentry", "approvalmax"],
  },
  {
    heading: "WORKFLOW TOOLS",
    icon: "shield",
    logos: ["microsoft 365", "google sheets"],
  },
];

export const CANADA_BOOKKEEPING = {
  badge: "Outsource Canada Bookkeeping & Accounting",
  titleBefore: "Canada Bookkeeping, Outsourced Accounting &",
  titleAccent: "Financial Cleanup",
  titleAfter: "Outsourcing Services",
  subtitle: "Reliable Bookkeeping, Accounting & Financial Cleanup Support for Canadian Accounting Firms",
  subtitleSecond:
    "Accurate bookkeeping is the foundation of every successful business. Streamline CRA-ready books with dedicated offshore delivery.",
  intro: {
    eyebrow: "Outsourcing Partnership",
    heading: "Reliable Bookkeeping Support for Growing Canadian Practices",
    paragraphs: [
      "Canadian businesses rely on timely financial records to meet Canada Revenue Agency (CRA) requirements, manage GST/HST obligations, monitor cash flow, and prepare reliable financial reports. As accounting firms continue to grow, managing bookkeeping, accounting, reconciliations, and financial cleanup projects for multiple clients can become increasingly resource-intensive.",
      "At NextLedgers, we provide dedicated offshore Bookkeeping, Outsourced Accounting & Financial Cleanup support to Canadian accounting firms, CPA practices, and bookkeeping providers. Our white-label outsourcing solutions help firms increase capacity, improve turnaround times, maintain compliance, and deliver accurate financial information without increasing internal staffing costs.",
    ],
    image: "/images/DSC09901.JPG",
  },
  whyMatter: {
    title: "Why Bookkeeping, Outsourced Accounting & Financial Cleanup Matter",
    intro:
      "Bookkeeping extends far beyond recording financial transactions. It involves maintaining accurate accounting records, reconciling accounts, organising financial data, reviewing historical records, correcting accounting errors, and ensuring businesses are prepared for GST/HST filings, payroll, year-end reporting, and CRA compliance.",
    bullets: [
      "Maintain accurate financial records",
      "Improve GST/HST compliance",
      "Strengthen CRA reporting readiness",
      "Improve cash flow visibility",
      "Reduce accounting errors",
      "Prepare for year-end reporting",
      "Improve business decision-making",
      "Reduce administrative workload",
    ],
  },
  sections: [
    {
      title: "Our Bookkeeping Services Include",
      items: [
        "Daily, Weekly & Monthly Bookkeeping",
        "Sales & Purchase Transaction Processing",
        "Bank & Credit Card Reconciliations",
        "Accounts Payable Processing",
        "Accounts Receivable Processing",
        "General Ledger Maintenance",
        "Journal Entry Processing",
        "Expense Categorisation & Coding",
        "Multi-Currency Bookkeeping",
        "Month-End Close Support",
        "Financial Data Validation",
        "Management Reporting Support",
      ],
    },
    {
      title: "Our Outsourced Accounting Services Include",
      items: [
        "Month-End Accounting Support",
        "Trial Balance Reviews",
        "General Ledger Reviews",
        "Accrual & Prepayment Entries",
        "Fixed Asset Register Maintenance",
        "Financial Statement Support",
        "Management Accounts Preparation",
        "Balance Sheet Reconciliations",
        "Working Paper Preparation",
        "Financial Reporting Support",
        "Internal Accounting Support",
        "Client-Ready Financial Reports",
      ],
    },
    {
      title: "Financial Cleanup & Catch-Up Accounting Services",
      intro:
        "Many businesses experience incomplete bookkeeping due to rapid growth, software migrations, staffing shortages, or historical accounting issues. Our financial cleanup services help restore accurate accounting records.",
      items: [
        "Catch-Up Bookkeeping",
        "Historical Transaction Reviews",
        "Backlog Transaction Processing",
        "Bank Reconciliation Cleanup",
        "General Ledger Cleanup",
        "Chart of Accounts Restructuring",
        "Suspense Account Clearance",
        "Error Identification & Correction",
        "Historical Accounting Adjustments",
        "Missing Financial Data Reconstruction",
        "Duplicate Transaction Reviews",
        "Financial Data Validation",
      ],
    },
    {
      title: "GST/HST-Ready Bookkeeping Support",
      intro: "Accurate bookkeeping is essential for reliable GST/HST compliance and CRA reporting.",
      items: [
        "GST/HST Coding Reviews",
        "Input Tax Credit (ITC) Reviews",
        "GST/HST Reconciliations",
        "Sales Tax Classification Reviews",
        "GST/HST Filing-Ready Reports",
        "CRA Audit-Ready Documentation",
        "Provincial Tax Classification Support",
        "GST/HST Working Papers",
      ],
    },
  ],
  howWeHelp: [
    "Increase bookkeeping capacity",
    "Improve turnaround times",
    "Reduce administrative workload",
    "Improve financial reporting accuracy",
    "Strengthen GST/HST compliance",
    "Improve CRA reporting readiness",
    "Deliver better client service",
    "Scale operations without increasing headcount",
  ],
  software: bookkeepingSoftware,
  industries: CANADA_INDUSTRIES,
  whyChoose: [
    "CPA-Led Delivery Team",
    "Canadian Bookkeeping & Accounting Expertise",
    "CRA & GST/HST Compliance Knowledge",
    "White-Label Service Delivery",
    "Dedicated Offshore Resources",
    "Structured Review Processes",
    "Secure Data Handling",
    "Flexible Engagement Models",
    "Scalable Support Framework",
  ],
  partner: {
    badge: "Bookkeeping & Accounting Partner",
    titleBefore: "Your Offshore",
    titleAccent: "Bookkeeping & Accounting Delivery Partner",
    body: "Whether you require support with day-to-day bookkeeping, outsourced accounting, financial cleanup projects, GST/HST-ready bookkeeping, reconciliations, management reporting, month-end close, or dedicated offshore bookkeeping resources, NextLedgers can help your practice scale efficiently while maintaining quality, compliance, and client satisfaction.",
  },
};

export const CANADA_CORPORATE_TAX = {
  badge: "Outsource Canada Corporate Tax Filing",
  titleBefore: "Canada Corporate Tax Filing",
  titleAccent: "Outsourcing Services",
  subtitle: "Reliable Corporate Tax Filing Support for Canadian Accounting Firms",
  subtitleSecond:
    "Increase capacity for T2 returns, CRA compliance, and tax working papers without adding headcount.",
  intro: {
    eyebrow: "Corporate Tax Partnership",
    heading: "Reliable Corporate Tax Filing Support for Growing Practices",
    paragraphs: [
      "Corporate tax compliance in Canada requires technical expertise, accuracy, and a thorough understanding of federal and provincial tax legislation. Preparing corporate tax returns, calculating taxable income, reviewing financial statements, reconciling accounting and tax differences, and complying with CRA requirements can be both complex and time-consuming.",
      "At NextLedgers, we provide dedicated offshore Corporate Tax Filing support to Canadian accounting firms, CPA practices, and tax advisory firms. Our white-label outsourcing solutions help firms increase capacity, improve turnaround times, and deliver reliable corporate tax compliance services without increasing internal staffing costs.",
    ],
    image: "/images/DSC09781.JPG",
  },
  whyMatter: {
    title: "Why Corporate Tax Filing Matters",
    intro:
      "Corporate tax filing involves far more than submitting an annual tax return. Businesses must accurately calculate taxable income, apply federal and provincial tax rules, identify allowable deductions, prepare supporting schedules, reconcile accounting records with tax computations, and maintain complete documentation.",
    bullets: [
      "Meet CRA filing deadlines",
      "Maintain compliance with Canadian tax legislation",
      "Improve tax reporting accuracy",
      "Reduce filing errors and reassessments",
      "Minimise penalties and interest charges",
      "Maintain complete tax documentation",
      "Support audit readiness",
      "Strengthen financial governance",
    ],
  },
  sections: [
    {
      title: "Our Corporate Tax Filing Services Include",
      items: [
        "T2 Corporate Income Tax Return Preparation Support",
        "Corporate Tax Computation Preparation",
        "Taxable Income Calculations",
        "Financial Statement Review for Tax Reporting",
        "Book-to-Tax Reconciliations",
        "Deduction & Expense Classification Reviews",
        "Capital Cost Allowance (CCA) Calculations",
        "Tax Adjustment Calculations",
        "Loss Carry Forward & Carry Back Reviews",
        "Deferred Tax Calculations",
        "Supporting Working Paper Preparation",
        "Filing-Ready Documentation Preparation",
      ],
    },
    {
      title: "CRA Compliance & Regulatory Reporting Support",
      items: [
        "CRA Compliance Reviews",
        "Supporting Tax Schedule Preparation",
        "Federal & Provincial Tax Reporting Support",
        "Prior-Year Adjustment Support",
        "Corporate Tax Amendment Support",
        "Tax Documentation Reviews",
        "Compliance Calendar Monitoring",
        "CRA Audit-Ready Documentation Preparation",
      ],
    },
    {
      title: "Corporate Tax Review & Reconciliation Support",
      items: [
        "Book-to-Tax Reconciliations",
        "Balance Sheet Reconciliations",
        "Tax Provision Reviews",
        "Non-Deductible Expense Reviews",
        "Capital Cost Allowance Reviews",
        "Temporary & Permanent Difference Reviews",
        "Financial Data Validation",
        "Tax Working Paper Preparation",
      ],
    },
    {
      title: "Corporate Tax Cleanup & Prior-Year Support",
      items: [
        "Prior-Year Tax Return Reviews",
        "Historical Tax Corrections",
        "Missed Deduction Reviews",
        "Financial Data Restatement Support",
        "Tax Record Cleanup",
        "CRA Amendment Documentation Support",
        "Historical Reconciliations",
        "Tax-Ready Financial Record Reconstruction",
      ],
    },
  ],
  howWeHelp: [
    "Increase tax preparation capacity",
    "Improve turnaround times",
    "Reduce compliance workload",
    "Improve filing accuracy",
    "Meet CRA deadlines efficiently",
    "Manage peak tax season workloads",
    "Improve client service delivery",
    "Scale operations without increasing headcount",
  ],
  software: [
    {
      heading: "TAX & ACCOUNTING SOFTWARE",
      icon: "user",
      logos: ["quickbooks online", "xero", "sage business cloud", "iris accounts production"],
    },
    {
      heading: "WORKING PAPER TOOLS",
      icon: "document",
      logos: ["dext", "hubdoc", "microsoft 365"],
    },
  ],
  industries: CANADA_INDUSTRIES,
  whyChoose: [
    "CPA-Led Delivery Team",
    "Canadian Corporate Tax Expertise",
    "CRA Compliance Knowledge",
    "Federal & Provincial Tax Understanding",
    "White-Label Service Delivery",
    "Dedicated Offshore Resources",
    "Structured Review Processes",
    "Secure Data Handling",
    "Flexible Engagement Models",
    "Scalable Support Framework",
  ],
  partner: {
    badge: "Corporate Tax Partner",
    titleBefore: "Your Offshore",
    titleAccent: "Corporate Tax Delivery Partner",
    body: "Whether you require support with T2 Corporate Income Tax returns, corporate tax computations, CRA compliance, tax reconciliations, capital cost allowance calculations, prior-year corrections, tax working papers, or dedicated offshore corporate tax resources, NextLedgers can help your practice scale efficiently while maintaining quality, compliance, and client satisfaction.",
  },
};

export const CANADA_GST_HST = {
  badge: "Outsource Canada GST/HST Compliance",
  titleBefore: "Canada GST / HST Compliance & CRA Compliance Support",
  titleAccent: "Outsourcing Services",
  subtitle: "Reliable GST / HST Compliance & CRA Reporting Support for Canadian Accounting Firms",
  subtitleSecond:
    "Strengthen CRA compliance and deliver accurate indirect tax reporting without increasing internal staffing costs.",
  intro: {
    eyebrow: "GST/HST Partnership",
    heading: "Reliable GST / HST Compliance Support for Growing Practices",
    paragraphs: [
      "GST/HST compliance is a critical component of financial management for Canadian businesses. Accounting firms must ensure GST/HST is accurately recorded, reconciled, and reported while complying with Canada Revenue Agency (CRA) regulations and varying provincial tax requirements. As client portfolios expand, managing GST/HST compliance across multiple businesses, provinces, and reporting periods can become increasingly time-consuming.",
      "At NextLedgers, we provide dedicated offshore GST / HST Compliance & CRA Compliance support to Canadian accounting firms, CPA practices, and bookkeeping providers. Our white-label outsourcing solutions help firms increase capacity, improve turnaround times, strengthen CRA compliance, and deliver accurate indirect tax reporting without increasing internal staffing costs.",
    ],
    image: "/images/DSC09794.JPG",
  },
  whyMatter: {
    title: "Why GST / HST Compliance Matters",
    intro:
      "GST/HST compliance involves much more than preparing periodic tax returns. Businesses must correctly classify taxable and exempt supplies, maintain accurate tax records, reconcile GST/HST accounts, maximise eligible Input Tax Credits (ITCs), and maintain supporting documentation to satisfy CRA requirements.",
    bullets: [
      "Meet CRA filing deadlines",
      "Maintain GST/HST compliance",
      "Improve tax reporting accuracy",
      "Maximise eligible Input Tax Credits (ITCs)",
      "Reduce filing errors and penalties",
      "Improve cash flow management",
      "Prepare for CRA audits",
      "Strengthen financial governance",
    ],
  },
  sections: [
    {
      title: "Our GST / HST Compliance Services Include",
      items: [
        "GST/HST Registration Support",
        "GST/HST Return Preparation Support",
        "Monthly, Quarterly & Annual GST/HST Filing Support",
        "GST/HST Account Reconciliations",
        "GST/HST Transaction Reviews",
        "GST/HST Coding Reviews",
        "Taxable & Exempt Supply Classification",
        "Input Tax Credit (ITC) Reviews",
        "GST/HST Working Paper Preparation",
        "GST/HST Compliance Reviews",
        "GST/HST Amendment Support",
        "Filing-Ready Documentation Preparation",
      ],
    },
    {
      title: "CRA Compliance & Regulatory Reporting Support",
      intro:
        "Our offshore team helps accounting firms maintain accurate reporting and ongoing compliance with CRA requirements.",
      items: [
        "CRA Compliance Reviews",
        "GST/HST Registration Assistance",
        "Supporting Schedule Preparation",
        "CRA Audit-Ready Documentation",
        "Filing Validation Reviews",
        "Prior-Period Adjustment Support",
        "Compliance Calendar Monitoring",
        "Regulatory Documentation Preparation",
      ],
    },
    {
      title: "GST / HST Review & Reconciliation Support",
      intro:
        "Accurate reconciliations ensure GST/HST returns are supported by complete and reliable accounting records.",
      items: [
        "GST/HST Control Account Reconciliations",
        "Sales Tax Reviews",
        "Purchase Tax Reviews",
        "Input Tax Credit Validation",
        "Historical GST/HST Reviews",
        "Tax Adjustment Calculations",
        "Provincial Tax Classification Reviews",
        "GST/HST Working Paper Preparation",
      ],
    },
    {
      title: "Multi-Province GST / HST Compliance Support",
      intro:
        "Businesses operating across multiple provinces often require additional review to ensure GST/HST has been applied correctly.",
      items: [
        "Province-Specific GST/HST Reviews",
        "Multi-Province Tax Classification",
        "Cross-Province Transaction Reviews",
        "Provincial Tax Rate Validation",
        "Multi-Entity GST/HST Support",
        "Intercompany GST/HST Reviews",
        "Cross-Border Transaction Reviews",
        "Compliance Documentation Support",
      ],
    },
  ],
  howWeHelp: [
    "Increase indirect tax compliance capacity",
    "Improve turnaround times",
    "Reduce compliance workload",
    "Improve GST/HST reporting accuracy",
    "Meet CRA filing deadlines",
    "Manage peak filing periods",
    "Improve client service delivery",
    "Scale operations without increasing headcount",
  ],
  software: [
    {
      heading: "ACCOUNTING SOFTWARE",
      icon: "user",
      logos: ["quickbooks online", "xero", "sage business cloud", "iris accounts production"],
    },
    {
      heading: "DOCUMENT PROCESSING TOOLS",
      icon: "document",
      logos: ["dext", "hubdoc", "autoentry", "approvalmax"],
    },
    {
      heading: "WORKFLOW TOOLS",
      icon: "shield",
      logos: ["microsoft 365"],
    },
  ],
  industries: CANADA_INDUSTRIES,
  whyChoose: [
    "CPAs-Led Delivery Team",
    "Canadian GST/HST Expertise",
    "CRA Compliance Knowledge",
    "Multi-Province Tax Experience",
    "White-Label Service Delivery",
    "Dedicated Offshore Resources",
    "Structured Review Processes",
    "Secure Data Handling",
    "Flexible Engagement Models",
    "Scalable Support Framework",
  ],
  partner: {
    badge: "GST/HST Compliance Partner",
    titleBefore: "Your Offshore",
    titleAccent: "GST / HST Compliance Delivery Partner",
    body: "Whether you require support with GST/HST registrations, GST/HST return preparation, Input Tax Credit (ITC) reviews, CRA compliance, GST/HST reconciliations, multi-province tax reporting, audit-ready working papers, or dedicated offshore indirect tax resources, NextLedgers can help your practice scale efficiently while maintaining quality, compliance, and client satisfaction.",
  },
};

export const CANADA_MANAGEMENT = {
  badge: "Outsource Canada Management Accounting & Virtual CFO",
  titleBefore: "Canada Management Accounting, Virtual CFO & Investment Accounting",
  titleAccent: "Outsourcing Services",
  subtitle:
    "Strategic Financial Leadership, Management Accounting & Investment Support for Canadian Businesses",
  subtitleSecond:
    "Strengthen financial reporting, improve decision-making, and scale advisory capabilities without increasing internal staffing costs.",
  intro: {
    eyebrow: "Management Accounting Partnership",
    heading: "Strategic Financial Leadership for Growing Canadian Practices",
    paragraphs: [
      "As Canadian businesses scale, financial decision-making becomes increasingly complex due to multi-channel revenue streams, provincial tax structures, capital allocation decisions, investor expectations, and regulatory reporting requirements under ASPE or IFRS. Management accounting and strategic financial oversight are no longer optional—they are essential for sustainable growth, profitability optimisation, and long-term financial stability.",
      "At NextLedgers, we provide dedicated offshore Management Accounting, Virtual CFO & Investment Accounting support to Canadian accounting firms, CPA practices, SMEs, and investment-driven businesses. Our white-label outsourcing solutions help firms strengthen financial reporting, improve decision-making, and scale advisory capabilities without increasing internal staffing costs.",
    ],
    image: "/images/DSC09879.JPG",
  },
  whyMatter: {
    title: "Why Management Accounting, Virtual CFO & Investment Accounting Matter",
    intro:
      "Modern businesses require more than historical bookkeeping—they need forward-looking financial intelligence. Management accounting and CFO-level insights help organisations understand performance, optimise costs, manage liquidity, evaluate investments, and make data-driven strategic decisions.",
    bullets: [
      "Improve profitability and cost efficiency",
      "Strengthen cash flow visibility and control",
      "Enhance budgeting and forecasting accuracy",
      "Support investment decision-making",
      "Improve capital allocation efficiency",
      "Strengthen financial governance",
      "Enable faster and better strategic decisions",
      "Increase investor and stakeholder confidence",
    ],
  },
  sections: [
    {
      title: "Our Management Accounting Services Include",
      items: [
        "Monthly Management Accounts Preparation",
        "Profit & Loss Reporting and Analysis",
        "Balance Sheet Reviews and Reconciliations",
        "Cash Flow Reporting and Analysis",
        "Budget vs Actual Performance Reporting",
        "KPI Tracking and Dashboard Preparation",
        "Variance Analysis Reporting",
        "Financial Performance Reviews",
      ],
    },
    {
      title: "Our Virtual CFO Services Include",
      items: [
        "Strategic Financial Planning and Oversight",
        "Business Performance Analysis",
        "Financial Modelling and Forecasting",
        "Scenario Planning and Decision Support",
        "Cost Structure Optimisation",
        "Executive-Level Financial Reporting",
        "Growth Strategy Financial Support",
        "Profitability Improvement Analysis",
      ],
    },
    {
      title: "Budgeting & Forecasting Support",
      intro: "We assist accounting firms and businesses with structured financial planning.",
      items: [
        "Annual Budget Preparation",
        "Rolling Forecast Updates",
        "Revenue and Expense Projections",
        "Departmental Budget Allocation",
        "Scenario-Based Financial Planning",
        "Variance Analysis and Reporting",
        "Financial Planning Models",
      ],
    },
    {
      title: "Cash Flow Management & Working Capital Analysis",
      intro: "Maintaining liquidity is critical for business stability and growth.",
      items: [
        "Cash Flow Forecasting",
        "Receivables and Payables Analysis",
        "Working Capital Optimisation",
        "Liquidity Monitoring and Reporting",
        "Payment Cycle Analysis",
        "Cash Position Reporting",
      ],
    },
    {
      title: "Investment Accounting & Portfolio Reporting Support",
      intro: "We provide structured accounting and reporting support for investment-driven businesses.",
      items: [
        "Investment Tracking and Reporting",
        "Portfolio Performance Analysis",
        "ROI (Return on Investment) Reporting",
        "Capital Allocation Tracking",
        "Asset Valuation Support",
        "Investment Reconciliation",
      ],
    },
    {
      title: "Business Performance & Advisory Insights",
      intro: "We transform financial data into actionable insights for strategic decision-making.",
      items: [
        "Financial KPI Development",
        "Margin and Profitability Analysis",
        "Cost Centre Reporting",
        "Business Unit Performance Tracking",
        "Executive Dashboard Reporting",
        "Strategic Financial Insights",
      ],
    },
  ],
  howWeHelp: [
    "Expand advisory and CFO service offerings",
    "Improve reporting capacity",
    "Deliver faster management insights",
    "Strengthen client decision-making support",
    "Reduce internal workload pressure",
    "Improve financial forecasting accuracy",
    "Scale advisory operations without increasing headcount",
    "Enhance client retention through value-added services",
  ],
  software: [
    {
      heading: "ACCOUNTING & REPORTING PLATFORMS",
      icon: "user",
      logos: ["quickbooks online", "xero", "sage business cloud", "microsoft 365"],
    },
    {
      heading: "INVESTMENT & REPORTING TOOLS",
      icon: "document",
      logos: ["iris accounts production", "dext", "hubdoc"],
    },
  ],
  industries: [...CANADA_INDUSTRIES, "Investment Holding Companies"],
  whyChoose: [
    "CPA-Led Delivery Team",
    "Canadian Management Accounting Expertise",
    "Virtual CFO & Advisory Capability",
    "Investment Reporting Support Experience",
    "White-Label Service Delivery",
    "Dedicated Offshore Resources",
    "Structured Review Processes",
    "Secure Data Handling",
    "Flexible Engagement Models",
    "Scalable Support Framework",
  ],
  partner: {
    badge: "Management Accounting Partner",
    titleBefore: "Your Offshore",
    titleAccent: "Management Accounting & CFO Delivery Partner",
    body: "Whether you require support with management accounts, budgeting, forecasting, financial modelling, KPI reporting, cash flow management, investment accounting, executive reporting, or dedicated offshore CFO resources, NextLedgers can help your practice scale efficiently while maintaining quality, accuracy, and client satisfaction.",
  },
};

export const CANADA_PAYROLL = {
  badge: "Outsource Canada Payroll Processing",
  titleBefore: "Canada Payroll Processing",
  titleAccent: "Outsourcing Services",
  subtitle: "End-to-End Payroll Processing and CRA-Compliant Payroll Management for Canadian Businesses",
  subtitleSecond:
    "Improve accuracy, ensure CRA compliance, and reduce internal payroll workload without increasing staffing costs.",
  intro: {
    eyebrow: "Payroll Partnership",
    heading: "Reliable Payroll Processing Support for Growing Practices",
    paragraphs: [
      "Payroll processing in Canada is highly regulated and increasingly complex due to evolving CRA requirements, province-specific employment standards, statutory deductions (CPP, EI, and income tax), and strict reporting deadlines. For accounting firms, CPA practices, and SMEs, ensuring payroll accuracy while managing compliance obligations and employee expectations can quickly become resource-intensive.",
      "At NextLedgers, we provide dedicated offshore Payroll Processing support to Canadian accounting firms, CPA practices, and businesses. Our white-label outsourcing solutions help firms improve accuracy, ensure CRA compliance, increase capacity, and reduce internal payroll workload without increasing staffing costs.",
    ],
    image: "/images/DSC09554.JPG",
  },
  whyMatter: {
    title: "Why Payroll Processing Matters",
    intro:
      "Payroll is not just about paying employees on time—it is a regulated financial process involving tax deductions, statutory compliance, employee benefits, and CRA reporting obligations.",
    bullets: [
      "Ensure accurate employee compensation",
      "Maintain CRA compliance",
      "Avoid penalties and interest charges",
      "Improve employee satisfaction",
      "Maintain accurate payroll records",
      "Manage statutory deductions correctly",
      "Support audit readiness",
      "Improve operational efficiency",
    ],
  },
  sections: [
    {
      title: "Payroll Calculation & Processing",
      intro: "Accurate and timely payroll execution aligned with Canadian payroll regulations.",
      items: [
        "Employee Salary Processing",
        "Hourly Wage and Overtime Calculations",
        "Bonus and Commission Processing",
        "Payslip Preparation Support",
        "Termination and Final Settlement Processing",
        "Payroll Cycle Management (Weekly, Bi-Weekly, Monthly)",
      ],
    },
    {
      title: "CRA Payroll Compliance & Remittances",
      intro: "Ensuring full compliance with CRA payroll obligations.",
      items: [
        "CPP, EI & Income Tax Deduction Calculations",
        "CRA Payroll Remittance Preparation",
        "Source Deduction Tracking",
        "Payroll Liability Reconciliation",
        "Compliance Validation Before Submission",
        "Year-End Payroll Compliance Support",
      ],
    },
    {
      title: "Payroll Tax & Statutory Deduction Management",
      intro: "Accurate handling of all statutory payroll obligations.",
      items: [
        "Federal and Provincial Tax Deductions",
        "Employee Benefit Deductions",
        "Pension Contribution Tracking",
        "Payroll Tax Mapping and Validation",
        "Deduction Reconciliation",
        "Payroll Register Reviews",
      ],
    },
    {
      title: "Multi-Province Payroll Support",
      intro: "Managing payroll across multiple Canadian jurisdictions with varying rules.",
      items: [
        "Province-Specific Payroll Compliance",
        "Multi-Location Payroll Processing",
        "Cross-Province Tax Rate Validation",
        "Regional Labour Law Alignment Support",
        "Payroll Structure Standardisation",
        "Jurisdiction-Based Reporting Consistency",
      ],
    },
    {
      title: "Payroll Reconciliation & Cleanup Services",
      intro: "Ensuring historical accuracy and resolving payroll discrepancies.",
      items: [
        "Historical Payroll Reconciliations",
        "Payroll Error Correction Entries",
        "Employee Record Validation",
        "Missing Payroll Data Reconstruction",
        "Payroll Audit Support Documentation",
        "Tax Deduction Corrections",
      ],
    },
    {
      title: "Year-End Payroll Reporting Support",
      intro: "Assisting with mandatory annual payroll filings.",
      items: [
        "T4 Slip Preparation Support",
        "T4A Reporting Assistance",
        "Year-End Payroll Reconciliations",
        "Employee Earnings Summaries",
        "CRA Filing Support Documentation",
        "Payroll-to-Accounting Reconciliation",
      ],
    },
  ],
  howWeHelp: [
    "Increase payroll processing capacity",
    "Reduce internal administrative workload",
    "Improve turnaround times",
    "Ensure CRA compliance accuracy",
    "Handle multi-client payroll efficiently",
    "Scale during peak payroll periods",
    "Improve client satisfaction",
    "Reduce operational risk",
  ],
  software: [
    {
      heading: "PAYROLL & ACCOUNTING PLATFORMS",
      icon: "user",
      logos: ["quickbooks online", "xero", "sage business cloud", "microsoft 365"],
    },
    {
      heading: "DOCUMENT & WORKFLOW TOOLS",
      icon: "document",
      logos: ["dext", "hubdoc", "approvalmax"],
    },
  ],
  industries: [...CANADA_INDUSTRIES, "Multi-location Franchise Businesses"],
  whyChoose: [
    "CPA-Led Delivery Team",
    "Canadian Payroll Compliance Expertise",
    "CRA Regulatory Understanding",
    "Multi-Province Payroll Experience",
    "White-Label Service Delivery",
    "Dedicated Offshore Resources",
    "Structured Review Processes",
    "Secure Data Handling",
    "Flexible Engagement Models",
    "Scalable Support Framework",
  ],
  partner: {
    badge: "Payroll Processing Partner",
    titleBefore: "Your Offshore",
    titleAccent: "Payroll Processing Delivery Partner",
    body: "Whether you require support with payroll calculations, CRA remittances, statutory deductions, multi-province payroll, year-end reporting, payroll reconciliations, or dedicated offshore payroll resources, NextLedgers can help your practice scale efficiently while maintaining accuracy, compliance, and client satisfaction.",
  },
};

export const CANADA_PERSONAL_TAX = {
  badge: "Outsource Canada Personal Tax Filing",
  titleBefore: "Canada Personal Tax Filing & CA Tax Preparation",
  titleAccent: "Outsourcing Services",
  subtitle:
    "Accurate, CRA-Compliant Personal Tax Filing & End-to-End Tax Preparation Services in Canada",
  subtitleSecond:
    "Improve capacity, enhance accuracy, and deliver compliant personal tax services without increasing internal staffing costs.",
  intro: {
    eyebrow: "Personal Tax Partnership",
    heading: "Reliable Personal Tax Filing Support for Growing Practices",
    paragraphs: [
      "Personal tax filing in Canada is becoming increasingly complex due to evolving Canada Revenue Agency (CRA) regulations, multiple income sources, provincial tax variations, investment income reporting, and strict filing deadlines. For individuals, self-employed professionals, and cross-border taxpayers, ensuring accurate tax filing while maximising eligible deductions and credits requires strong technical understanding of Canadian tax laws.",
      "At NextLedgers, we provide dedicated offshore Canada Personal Tax Filing & CA Tax Preparation services to CPA firms, tax advisors, and accounting practices. Our white-label outsourcing solutions help firms improve capacity, enhance accuracy, and deliver compliant personal tax services without increasing internal workload or staffing costs.",
    ],
    image: "/images/DSC09669.JPG",
  },
  whyMatter: {
    title: "Why Personal Tax Filing Matters",
    intro:
      "Personal tax filing is not just a compliance requirement—it directly impacts refunds, tax liabilities, and long-term financial planning. Accurate filing ensures that all eligible deductions and credits are claimed while maintaining full compliance with CRA requirements.",
    bullets: [
      "Ensure CRA compliance",
      "Maximise eligible tax refunds",
      "Reduce risk of penalties and interest",
      "Improve accuracy in income reporting",
      "Optimise deductions and tax credits",
      "Maintain proper financial documentation",
      "Support audit readiness",
      "Improve filing efficiency during tax season",
    ],
  },
  sections: [
    {
      title: "Personal Income Tax Preparation & Filing",
      intro: "Accurate preparation and filing of Canadian personal tax returns.",
      items: [
        "T1 General Tax Return Preparation Support",
        "Employment Income Reporting",
        "Multi-Source Income Reconciliation",
        "Self-Employment Income Classification",
        "Filing-Ready Tax Document Preparation",
        "CRA E-Filing Support Assistance",
      ],
    },
    {
      title: "Self-Employed & Freelancer Tax Support",
      intro: "Specialised support for independent professionals and gig workers.",
      items: [
        "Business Income and Expense Classification",
        "Home Office Expense Calculations",
        "Mileage and Travel Expense Tracking",
        "GST/HST Integration Support for Self-Employed Clients",
        "Profit and Loss Adjustments",
        "Deduction Tracking and Validation",
      ],
    },
    {
      title: "Investment & Capital Gains Tax Reporting",
      intro: "Accurate reporting of investment-related income and gains.",
      items: [
        "Capital Gains and Losses Calculation",
        "Dividend Income Reporting (Eligible and Non-Eligible)",
        "Interest Income Classification",
        "Investment Portfolio Reconciliation",
        "Crypto Asset Tax Reporting Support",
        "Tax-Efficient Gain/Loss Analysis",
      ],
    },
    {
      title: "Tax Deduction & Credit Optimisation",
      intro: "Ensuring clients maximise eligible CRA benefits.",
      items: [
        "RRSP Contribution Tracking",
        "Tuition and Education Credits Support",
        "Medical Expense Calculations",
        "Charitable Donation Tracking",
        "Childcare and Family Deductions",
        "Provincial Tax Credit Analysis",
      ],
    },
    {
      title: "Tax Cleanup & Prior-Year Filing Support",
      intro: "Supporting backlog and correction of historical tax issues.",
      items: [
        "Prior-Year T1 Tax Return Preparation",
        "Amended Return (T1 Adjustment) Support",
        "Missing Income Corrections",
        "Backlog Tax Filing Cleanup",
        "CRA Notice Response Support",
        "Financial Record Reconstruction",
      ],
    },
    {
      title: "Multi-Source & Complex Income Tax Support",
      intro: "Managing diversified income structures and complex cases.",
      items: [
        "Employment + Self-Employment Income Consolidation",
        "Rental Income Reporting",
        "Cross-Border Income Reporting Support",
        "Multiple T-Slip Reconciliation",
        "Pension and Retirement Income Reporting",
        "Complex Deduction Structuring",
      ],
    },
  ],
  howWeHelp: [
    "Increase tax season capacity",
    "Improve turnaround times",
    "Reduce internal workload pressure",
    "Enhance accuracy in filings",
    "Improve client refund outcomes",
    "Manage peak-season demand efficiently",
    "Scale tax operations without hiring locally",
    "Strengthen client satisfaction and retention",
  ],
  software: [
    {
      heading: "ACCOUNTING PLATFORMS",
      icon: "user",
      logos: ["quickbooks online", "xero", "sage business cloud", "microsoft 365"],
    },
    {
      heading: "DOCUMENT PROCESSING TOOLS",
      icon: "document",
      logos: ["dext", "hubdoc", "iris accounts production"],
    },
  ],
  industries: [
    "Salaried Professionals",
    "Self-Employed Individuals",
    "Freelancers & Contractors",
    "High-Net-Worth Individuals",
    "Cross-Border Taxpayers",
    "Real Estate Investors",
    "Small Business Owners",
  ],
  whyChoose: [
    "CPA-Led Delivery Team",
    "Canadian Personal Tax Expertise",
    "CRA Compliance Knowledge",
    "Multi-Source Income Handling Experience",
    "White-Label Service Delivery",
    "Dedicated Offshore Resources",
    "Structured Review Processes",
    "Secure Data Handling",
    "Flexible Engagement Models",
    "Scalable Support Framework",
  ],
  partner: {
    badge: "Personal Tax Partner",
    titleBefore: "Your Offshore",
    titleAccent: "Personal Tax Preparation Partner",
    body: "Whether you require support with T1 tax preparation, self-employed tax filing, investment income reporting, capital gains calculations, prior-year tax cleanup, deduction optimisation, or dedicated offshore personal tax resources, NextLedgers can help your practice scale efficiently while maintaining quality, compliance, and client satisfaction.",
  },
};

export const CANADA_REVIEW = {
  badge: "Outsource Canada Review Engagements",
  titleBefore: "Canada Review Engagement, Compliance & Assurance Services",
  titleAccent: "Outsourcing",
  subtitle:
    "Reliable Review Engagements, Assurance Services & CRA-Aligned Financial Compliance Support in Canada",
  subtitleSecond:
    "Improve capacity, strengthen working paper preparation, and deliver high-quality review engagements while reducing internal workload.",
  intro: {
    eyebrow: "Review Engagement Partnership",
    heading: "Reliable Review Engagement Support for Growing Practices",
    paragraphs: [
      "Review engagements in Canada play a key role in providing limited assurance on financial statements for private enterprises that do not require a full statutory audit. With increasing CRA scrutiny, lender expectations, and stakeholder demands, businesses must ensure financial reporting is accurate, consistent, and compliant with applicable accounting frameworks such as ASPE and IFRS.",
      "At NextLedgers, we provide dedicated offshore Review Engagement, Compliance & Assurance support services for Canadian CPA firms and accounting practices. Our white-label solutions help firms improve capacity, strengthen working paper preparation, and deliver high-quality review engagements while reducing internal workload and operational pressure.",
    ],
    image: "/images/DSC09486.JPG",
  },
  whyMatter: {
    title: "Why Review Engagements & Assurance Services Matter",
    intro:
      "Review engagements provide limited assurance that financial statements are plausible and free from material misstatement. They enhance stakeholder confidence without the depth of a full audit, making them a critical service for private enterprises.",
    bullets: [
      "Improve financial statement credibility",
      "Ensure consistency in reporting",
      "Identify accounting inconsistencies early",
      "Strengthen CRA and regulatory alignment",
      "Enhance investor and lender confidence",
      "Reduce financial reporting risk",
      "Support audit-readiness where required",
      "Improve governance and transparency",
    ],
  },
  sections: [
    {
      title: "Review Engagement File Preparation Support",
      intro: "Structured preparation of working papers and financial documentation.",
      items: [
        "Financial Statement Compilation Support",
        "Trial Balance Validation and Reconciliation",
        "Working Paper Preparation and Organisation",
        "Analytical Review Schedules Preparation",
        "Supporting Documentation Collation",
        "Pre-Engagement File Structuring",
      ],
    },
    {
      title: "Financial Statement Analysis & Consistency Checks",
      intro: "Ensuring financial statements are accurate and internally consistent.",
      items: [
        "Profit & Loss Analysis",
        "Balance Sheet Consistency Checks",
        "Account Classification Validation",
        "Variance and Trend Analysis",
        "Inter-Period Comparisons",
        "Error Identification and Correction Support",
      ],
    },
    {
      title: "Analytical Procedures & Assurance Support",
      intro: "Supporting required analytical procedures under review engagement standards.",
      items: [
        "Ratio Analysis (Liquidity, Profitability, Solvency)",
        "Revenue and Expense Trend Analysis",
        "Budget vs Actual Comparisons",
        "Material Fluctuation Analysis",
        "Industry Benchmarking Support",
        "Analytical Working Paper Preparation",
      ],
    },
    {
      title: "CRA Compliance & Reporting Alignment",
      intro: "Ensuring alignment between financial reporting and CRA filings.",
      items: [
        "Accounting-to-Tax Reconciliation Support",
        "GST/HST Alignment Checks",
        "Corporate Tax Linkage Validation (T2 Alignment Support)",
        "Adjustment Entry Reviews",
        "Compliance Consistency Checks",
        "Audit-Ready Documentation Preparation",
      ],
    },
    {
      title: "Cleanup & Pre-Engagement Adjustments",
      intro: "Resolving inconsistencies before review engagement execution.",
      items: [
        "Historical Bookkeeping Adjustments",
        "Reclassification of Accounts",
        "Missing Transaction Identification",
        "Bank and Ledger Reconciliations",
        "Prior-Period Correction Entries",
        "Financial Data Restructuring",
      ],
    },
    {
      title: "Multi-Entity Review Support",
      intro: "Supporting consolidated reporting and group structures.",
      items: [
        "Intercompany Reconciliation Support",
        "Consolidated Financial Statement Preparation Support",
        "Entity-Level Financial Validation",
        "Group Reporting Schedules",
        "Cross-Entity Consistency Checks",
        "Consolidation Adjustment Support",
      ],
    },
  ],
  howWeHelp: [
    "Increase engagement capacity",
    "Improve turnaround times",
    "Reduce internal preparation workload",
    "Enhance working paper quality",
    "Strengthen compliance consistency",
    "Manage peak-season demand efficiently",
    "Improve client reporting quality",
    "Scale assurance services without hiring locally",
  ],
  software: [
    {
      heading: "CORE ACCOUNTING PLATFORMS",
      icon: "user",
      logos: ["quickbooks online", "xero", "sage business cloud", "microsoft 365"],
    },
    {
      heading: "REVIEW & ASSURANCE TOOLS",
      icon: "document",
      logos: ["iris accounts production", "dext", "hubdoc"],
    },
  ],
  industries: [...CANADA_INDUSTRIES, "Multi-Entity Groups"],
  whyChoose: [
    "CPA-Led Delivery Team",
    "Canadian Review Engagement Expertise",
    "CPA Canada Standards Understanding",
    "ASPE / IFRS Reporting Alignment",
    "White-Label Service Delivery",
    "Dedicated Offshore Resources",
    "Structured Review Processes",
    "Secure Data Handling",
    "Flexible Engagement Models",
    "Scalable Support Framework",
  ],
  partner: {
    badge: "Review Engagement Partner",
    titleBefore: "Your Offshore",
    titleAccent: "Review Engagement & Assurance Delivery Partner",
    body: "Whether you require support with review engagement file preparation, financial statement analysis, analytical procedures, CRA alignment, working paper structuring, or dedicated offshore assurance resources, NextLedgers can help your practice scale efficiently while maintaining quality, compliance, and client satisfaction.",
  },
};

export const CANADA_YEAR_END = {
  badge: "Outsource Canada Year-End Accounts",
  titleBefore: "Canada Year-End Accounts & Financial Statement Preparation Services",
  titleAccent: "Outsourcing",
  subtitle:
    "Accurate, CRA-Compliant Year-End Financial Reporting & Financial Statement Preparation for Canadian Businesses",
  subtitleSecond:
    "Accelerate year-end close, strengthen reporting accuracy, and reduce internal workload with experienced offshore accounting professionals.",
  intro: {
    eyebrow: "Year-End Accounts Partnership",
    heading: "Reliable Year-End Accounts Support for Growing Practices",
    paragraphs: [
      "Year-end accounts preparation is one of the most important financial reporting obligations for Canadian businesses. Whether preparing financial statements for shareholders, lenders, investors, management, or supporting corporate tax filings with the Canada Revenue Agency (CRA), organisations need accurate, complete, and compliant financial information to close their financial year with confidence.",
      "At NextLedgers, we provide dedicated offshore Canada Year-End Accounts & Financial Statement Preparation Services for Canadian CPA firms, accounting practices, SMEs, and multi-entity organisations. Our white-label accounting solutions help firms accelerate year-end close processes, strengthen financial reporting accuracy, improve CRA compliance readiness, and reduce internal workload through experienced offshore accounting professionals.",
    ],
    image: "/images/DSC09894.JPG",
  },
  whyMatter: {
    title: "Why Year-End Accounts & Financial Statement Preparation Matter",
    intro:
      "Accurate year-end financial statements provide the foundation for regulatory compliance, tax reporting, business planning, and informed decision-making. A well-managed year-end close ensures financial information is reliable, complete, and ready for internal and external stakeholders.",
    bullets: [
      "Improve financial reporting accuracy",
      "Accelerate year-end close timelines",
      "Strengthen CRA compliance readiness",
      "Reduce reconciliation errors",
      "Maintain ASPE and IFRS reporting consistency",
      "Improve audit preparedness",
      "Enhance lender and investor confidence",
      "Support informed business decisions",
      "Reduce pressure on internal finance teams",
      "Scale accounting capacity during peak reporting periods",
    ],
  },
  sections: [
    {
      title: "Year-End Closing & Financial Statement Preparation",
      intro:
        "Supporting businesses throughout the financial close process with accurate financial statement preparation and structured year-end reporting.",
      items: [
        "Income Statement (Profit & Loss) Preparation",
        "Balance Sheet Preparation",
        "Trial Balance Review and Validation",
        "Year-End Accruals and Prepayments",
        "Depreciation and Amortisation Calculations",
        "Fixed Asset Schedule Preparation",
        "Financial Statement Compilation Support",
        "Working Paper Preparation",
      ],
    },
    {
      title: "Book-to-Year-End Reconciliation Support",
      intro: "Ensuring accounting records are fully reconciled before finalising financial statements.",
      items: [
        "Bank Reconciliations",
        "General Ledger Reconciliations",
        "Accounts Receivable Reconciliation",
        "Accounts Payable Reconciliation",
        "Intercompany Reconciliations",
        "GST/HST Reconciliations",
        "Suspense Account Clearance",
        "Revenue and Expense Validation",
      ],
    },
    {
      title: "Year-End Journal Entries & Financial Adjustments",
      intro: "Preparing accurate accounting adjustments required for complete financial reporting.",
      items: [
        "Accrual and Deferral Entries",
        "Depreciation Journal Entries",
        "Fixed Asset Adjustments",
        "Provision and Reserve Calculations",
        "Prepaid Expense Adjustments",
        "Reclassification Journal Entries",
        "Error Correction Entries",
        "Tax Adjustment Support",
      ],
    },
    {
      title: "Management & Statutory Financial Reporting",
      intro:
        "Preparing professional financial reports for management, stakeholders, lenders, and statutory purposes.",
      items: [
        "Annual Financial Statements",
        "Management Accounts",
        "Comparative Financial Reporting",
        "Cash Flow Statement Preparation",
        "Notes to Financial Statements",
        "Board Reporting Packs",
        "Executive Reporting Summaries",
        "Financial Disclosure Support",
      ],
    },
    {
      title: "CRA Compliance & Tax Readiness Support",
      intro: "Helping ensure year-end financial statements align with Canadian tax reporting requirements.",
      items: [
        "Financial Statement to T2 Reconciliation Support",
        "GST/HST Year-End Alignment",
        "Corporate Tax Adjustment Support",
        "Deferred Tax Reconciliation Assistance",
        "Supporting Schedules for Tax Preparation",
        "CRA-Ready Working Papers",
        "Audit-Ready Financial Documentation",
        "Year-End Compliance Reviews",
      ],
    },
    {
      title: "Financial Cleanup & Backlog Accounting",
      intro: "Resolving historical accounting issues before finalising year-end financial statements.",
      items: [
        "Historical Bookkeeping Cleanup",
        "Prior-Period Adjustments",
        "Missing Transaction Identification",
        "Ledger Restructuring",
        "Chart of Accounts Optimisation",
        "Financial Record Validation",
        "Historical Reconciliation Support",
        "Audit Preparation Cleanup",
      ],
    },
  ],
  howWeHelp: [
    "Reduce year-end workload",
    "Close financial periods faster",
    "Improve reporting quality",
    "Increase accounting team capacity",
    "Strengthen reconciliation accuracy",
    "Improve financial statement consistency",
    "Reduce reporting risks",
    "Support busy season requirements",
    "Deliver audit-ready financial information",
    "Scale finance operations without increasing overhead",
  ],
  software: [
    {
      heading: "CORE ACCOUNTING PLATFORMS",
      icon: "user",
      logos: ["quickbooks online", "xero", "sage business cloud", "microsoft 365"],
    },
    {
      heading: "FINANCIAL REPORTING & YEAR-END SOFTWARE",
      icon: "document",
      logos: ["iris accounts production", "dext", "hubdoc"],
    },
  ],
  industries: [
    ...CANADA_INDUSTRIES,
    "Not-for-Profit Organisations",
    "Multi-Entity & Group Businesses",
  ],
  whyChoose: [
    "Experienced Offshore Accounting Professionals",
    "Dedicated Support for Canadian CPA Firms",
    "CRA Reporting & Compliance Understanding",
    "ASPE & IFRS Financial Reporting Expertise",
    "White-Label Delivery Model",
    "Secure & Confidential Data Handling",
    "Flexible Engagement Models",
    "Scalable Offshore Accounting Teams",
    "Structured Year-End Close Processes",
    "Reliable Turnaround During Peak Reporting Seasons",
  ],
  partner: {
    badge: "Year-End Accounts Partner",
    titleBefore: "Your Offshore Partner for",
    titleAccent: "Canada Year-End Accounts & Financial Statement Preparation",
    body: "Whether you require support with year-end close activities, financial statement preparation, account reconciliations, journal entries, CRA compliance readiness, or dedicated offshore accounting resources, our professionals provide dependable, scalable solutions tailored to your firm's needs.",
  },
};
